import { courses, instituteInfo } from "../data/courses";

export const seoConfig = {
  siteName: instituteInfo.name,
  shortName: instituteInfo.shortName,
  siteUrl: "https://next-generation-academy.vercel.app",
  canonicalPath: "/",
  title: "Next Generation Academy | Computer, Digital Marketing & Safety Courses",
  description:
    "Join Next Generation Academy for practical computer, web development, Python, data science, Tally, digital marketing, graphic design, and safety officer training.",
  keywords: [
  // Brand Keywords
  "Next Generation Academy",
  "Next Generation Academy Deoria",
  "Next Generation Academy Pathardeva",
  "Next Generation Academy Baghauch Ghat",
  "Next Generation Academy Baghauch",
  "Next Generation Academy Baghauchghat",
  "Next Generation Academy Baghauch Ghat Deoria",
  "Next Generation Academy Deoria Uttar Pradesh",
  "NGA Deoria",
  "NGA Baghauch Ghat",
  "NGA Baghauch",
  "NGA Pathardeva",
  "Next Generation Academy near me",
  "Next Generation Academy nearby",
  "Next Generation Academy admission",
  "Next Generation Academy courses",
  "Next Generation Academy training institute",

  // Local Computer Institute Keywords
  "computer institute Deoria",
  "computer institute Baghauch Ghat",
  "computer institute Baghauch",
  "computer institute Pathardeva",
  "computer institute Baghauch Ghat Deoria",
  "computer training institute Deoria",
  "computer training institute Baghauch",
  "computer training institute Pathardeva",
  "computer courses Deoria",
  "computer courses Baghauch",
  "computer courses Baghauch Ghat",
  "computer courses Pathardeva",
  "computer courses Narayanpur",
  "computer classes Deoria",
  "computer classes Baghauch",
  "computer classes Baghauch Ghat",
  "computer classes Pathardeva",
  "computer coaching Deoria",
  "computer coaching Baghauch",
  "computer coaching Baghauch Ghat",
  "best computer institute in Deoria",
  "best computer institute in Baghauch",
  "best computer institute in Baghauch Ghat",
  "best computer institute near Pathardeva",
  "computer education Deoria",
  "computer education Baghauch",
  "computer training Deoria",

  // Web Development
  "web development course",
  "web development course Deoria",
  "web development course Baghauch",
  "web development course Baghauch Ghat",
  "web development course Pathardeva",
  "web designing course Deoria",
  "web designing course Baghauch",
  "web designing course Baghauch Ghat",
  "web development institute Deoria",
  "web development institute Baghauch",
  "web development training Deoria",
  "full stack development course Deoria",
  "full stack web development course",
  "full stack developer course Deoria",
  "frontend development course Deoria",
  "backend development course Deoria",
  "HTML CSS JavaScript course Deoria",
  "React JS course Deoria",
  "Node JS course Deoria",
  "JavaScript course Deoria",

  // Programming
  "programming course Deoria",
  "programming course Baghauch",
  "coding classes Deoria",
  "coding classes Baghauch",
  "coding institute Deoria",
  "coding institute Baghauch",
  "Python programming course",
  "Python course Deoria",
  "Python course Baghauch",
  "Python programming course Deoria",
  "Python programming course Baghauch",
  "Python classes Deoria",
  "Python training Deoria",
  "C programming course Deoria",
  "C++ programming course Deoria",
  "C language course Deoria",
  "C++ course Deoria",

  // Data Science & AI
  "data science course",
  "data science course Deoria",
  "data science course Baghauch",
  "data science institute Deoria",
  "data science training Deoria",
  "data analytics course Deoria",
  "data analytics course Baghauch",
  "machine learning course Deoria",
  "machine learning course Baghauch",
  "AI course Deoria",
  "artificial intelligence course Deoria",
  "AI training Deoria",
  "data science classes Deoria",

  // Tally & Accounting
  "Tally course",
  "Tally course Deoria",
  "Tally course Baghauch",
  "Tally course Baghauch Ghat",
  "Tally classes Deoria",
  "Tally training Deoria",
  "Tally institute Deoria",
  "Tally Prime course Deoria",
  "Tally Prime training Deoria",
  "accounting course Deoria",
  "computer accounting course Deoria",
  "GST course Deoria",
  "Tally GST course Deoria",
  "Tally with GST course",
  "accounting classes Baghauch",

  // Digital Marketing
  "digital marketing course",
  "digital marketing course Deoria",
  "digital marketing course Baghauch",
  "digital marketing course Baghauch Ghat",
  "digital marketing institute Deoria",
  "digital marketing training Deoria",
  "digital marketing classes Deoria",
  "SEO course Deoria",
  "SEO training Deoria",
  "social media marketing course Deoria",
  "online marketing course Deoria",
  "digital marketing institute Baghauch",

  // Safety Officer
  "safety officer course",
  "safety officer course Deoria",
  "safety officer course Baghauch",
  "safety officer training Deoria",
  "safety officer institute Deoria",
  "industrial safety course Deoria",
  "fire safety course Deoria",
  "health and safety course Deoria",
  "safety training institute Deoria",

  // Skill Development
  "skill training institute",
  "skill development institute Deoria",
  "skill development institute Baghauch",
  "skill development courses Deoria",
  "vocational training institute Deoria",
  "professional training institute Deoria",
  "job oriented courses Deoria",
  "job oriented computer courses Deoria",
  "career training institute Deoria",
  "career development courses Deoria",
  "computer skill development Deoria",

  // Nearby Locations
  "computer institute near Baghauch Ghat",
  "computer institute near Baghauch",
  "computer institute near Pathardeva",
  "computer institute near Narayanpur",
  "computer institute near Deoria",
  "computer classes near Baghauch Ghat",
  "computer classes near Baghauch",
  "computer classes near Pathardeva",
  "computer courses near Baghauch Ghat",
  "computer courses near Pathardeva",
  "computer training near Baghauch",
  "computer training near Pathardeva",
  "computer institute in Deoria district",
  "computer training in Deoria district",

  // Admission / Intent Keywords
  "computer course admission Deoria",
  "computer course admission Baghauch",
  "computer institute admission Deoria",
  "computer courses after 12th Deoria",
  "computer courses after 10th Deoria",
  "best computer course Deoria",
  "best computer course Baghauch",
  "best computer institute Deoria",
  "best computer institute Baghauch Ghat",
  "best skill institute Deoria",
  "affordable computer courses Deoria",
  "computer courses with certificate Deoria",
  "professional computer courses Deoria",
  "computer training with certificate Deoria"
],
  image: "/site-icon.jpeg",
  locale: "en_IN",
};

export const getCanonicalUrl = (path = seoConfig.canonicalPath) =>
  new URL(path, seoConfig.siteUrl).toString();

export const jsonLd = [
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: seoConfig.siteName,
    url: seoConfig.siteUrl,
    inLanguage: "en-IN",
  },
  {
    "@context": "https://schema.org",
    "@type": ["Organization", "LocalBusiness"],
    name: instituteInfo.name,
    alternateName: instituteInfo.shortName,
    url: seoConfig.siteUrl,
    logo: getCanonicalUrl(seoConfig.image),
    image: getCanonicalUrl(seoConfig.image),
    telephone: instituteInfo.phone,
    email: instituteInfo.email,
    address: {
      "@type": "PostalAddress",
      streetAddress: instituteInfo.address,
      addressCountry: "IN",
    },
    openingHours: "Mo-Sa 07:00-18:00",
    slogan: instituteInfo.tagline,
  },
  {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: "Courses at Next Generation Academy",
    itemListElement: courses.map((course, index) => ({
      "@type": "ListItem",
      position: index + 1,
      item: {
        "@type": "Course",
        name: course.title,
        description: course.description,
        provider: {
          "@type": "Organization",
          name: instituteInfo.name,
          sameAs: seoConfig.siteUrl,
        },
        offers: {
          "@type": "Offer",
          priceCurrency: "INR",
          price: course.fees.replace(/[^0-9]/g, ""),
          availability: "https://schema.org/InStock",
          url: getCanonicalUrl("/#courses"),
        },
      },
    })),
  },
  {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: seoConfig.siteUrl,
      },
    ],
  },
];
